name: CI
on:
  push:
    branches: [ "main", "demo1" ]
  pull_request:
    branches: [ "main", "demo1" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - run: pytest tests/